Web/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Entities;

namespace Web.Controllers
{
    public class SettingController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: SettingEntities
        public ActionResult Index()
        {
            return View("Index",db.SettingEntities.ToList());
        }

        // GET: SettingEntities/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingEntity settingEntity = db.SettingEntities.Find(id);
            if (settingEntity == null)
            {
                return HttpNotFound();
            }
            return View(settingEntity);
        }

        // GET: SettingEntities/Create
        public ActionResult Create()
        {
            SelectList categories = new SelectList(db.Categories.ToList(), "Id", "Name");
            ViewBag.Categories = categories;
            return View();
        }

        // POST: SettingEntities/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/*[Bind(Include = "Id,PicturesCount")]*/ SettingEntity settingEntity)
        {
            if (ModelState.IsValid)
            {
                settingEntity.Id = Guid.NewGuid();
                db.SettingEntities.Add(settingEntity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(settingEntity);
        }

        // GET: SettingEntities/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingEntity settingEntity = db.SettingEntities.Find(id);
            if (settingEntity == null)
            {
                return HttpNotFound();
            }
            return View(settingEntity);
        }

        // POST: SettingEntities/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PicturesCount")] SettingEntity settingEntity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(settingEntity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(settingEntity);
        }

        // GET: SettingEntities/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SettingEntity settingEntity = db.SettingEntities.Find(id);
            if (settingEntity == null)
            {
                return HttpNotFound();
            }
            return View(settingEntity);
        }

        // POST: SettingEntities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            SettingEntity settingEntity = db.SettingEntities.Find(id);
            db.SettingEntities.Remove(settingEntity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Gallery", "Index", "Home")</li>
                    <li>@Html.ActionLink("Categories", "CategoriesList", "Home")</li>
                    <li>@Html.ActionLink("Settings", "Index", "Setting")</li>
                    <li>@Html.ActionLink("ByCategories", "IndexByCategoriesAsync", "Home")</li>
                    <li>@Html.ActionLink("FromIngur", "ShowPicture", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

 
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>